# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
k_bio = "Kendrick Lamar Duckworth (born June 17, 1987), better known simply as Kendrick Lamar, is an American rapper, and songwriter from Compton. He first gained major attention after the release of his 2010 mixtape O(verly) D(edicated). In 2011, his album Section.80, released exclusively through iTunes, instantly ranked as one of the top digital hip-hop releases of the year. In 2012, he crossed over to mainstream audiences with his major label debut good kid, m.A.A.d city which was widely regarded as an instant classic. In 2015, he dropped To Pimp a Butterfly to widespread acclaim.Known for his storytelling, imagery, wordplay, and internal & multisyllabic rhyme schemes coupled with songwriting ability, the proclaimed “Nas of the West Coast” brings hard-hitting lyricism with narratives of Los Angeles, a region known for its more straightforward artists.Lamar is a member of the hip-hop collective Black Hippy, along with Jay Rock, Schoolboy Q, and Ab-Soul. He is also signed to Dr. Dre’s Aftermath Entertainment imprint label under Interscope Records."
q_bio = "Quincy Matthew Hanley (born October 26, 1986), better known by his stage name Schoolboy Q (often stylized ScHoolboy Q), is an American hip hop recording artist from South Central Los Angeles, California. Signed to Top Dawg Entertainment and Interscope Records, Hanley is a member of hip hop supergroup Black Hippy, along with fellow West Coast rappers and label-mates Ab-Soul, Jay Rock, and Kendrick Lamar Preceded by two mixtapes, his first independent album Setbacks, released January 11, 2011, reached #100 on the US Billboard 200 chart, selling close to 1,000 digital copies in the first week. Almost a year later on January 14, 2012, he released his second independent album Habits & Contradictions. The album debuted at #111 on the US Billboard 200, with first-week sales of 3,900 digital copies in the United States. His major label debut studio album, entitled Oxymoron, was released on February 25th, 2014 & got a 81 out of 100 on Metacritic"
kw_bio = "The ubiquitous Kanye West. From his famous quip, “George Bush doesn’t care about black people” to “I'ma let you finish” to marrying Kim Kardashian, you can see that he’s a staple in the tabloids and blog posts. But that certainly doesn’t take anything away from his music. As matter of fact, it makes it better. For instance, his 2010 solo album, My Beautiful Dark Twisted Fantasy was universally praised by fans and critics alike; it was recorded during the backlash he received from the Swift interruption and during his break-up with then girlfriend Amber Rose. He has scored other well known hits as well from each of his previous studio albums, such as “Stronger,” “Homecoming,” and “Gold Digger.” Each of his albums have been massive critical and commercial successes, including his collaboration album with Jay-Z, Watch the Throne. Kanye’s most recent project was Yeezus, his sixth solo album, which polarized his fan base and the general public, but was heaped with rave reviews by music critics."
Artist.create(name:"Kendrick Lamar", img:"https://flavorwire.files.wordpress.com/2014/12/kendrick.jpg", bio:k_bio)
Artist.create(name:"Schoolboy Q", img:"http://images.rapgenius.com/0fa28463260e245a4876dbda4609d692.576x384x1.jpg", bio:q_bio)
Artist.create(name:"Kanye West", img:"http://cdn.papermag.com/uploaded_images/kanye-west1.jpg", bio:kw_bio)
