# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
k_bio = "Kendrick Lamar Duckworth (born June 17, 1987), better known simply as Kendrick Lamar, is an American rapper, and songwriter from Compton. He first gained major attention after the release of his 2010 mixtape O(verly) D(edicated). In 2011, his album Section.80, released exclusively through iTunes, instantly ranked as one of the top digital hip-hop releases of the year. In 2012, he crossed over to mainstream audiences with his major label debut good kid, m.A.A.d city which was widely regarded as an instant classic. In 2015, he dropped To Pimp a Butterfly to widespread acclaim.Known for his storytelling, imagery, wordplay, and internal & multisyllabic rhyme schemes coupled with songwriting ability, the proclaimed “Nas of the West Coast” brings hard-hitting lyricism with narratives of Los Angeles, a region known for its more straightforward artists.Lamar is a member of the hip-hop collective Black Hippy, along with Jay Rock, Schoolboy Q, and Ab-Soul. He is also signed to Dr. Dre’s Aftermath Entertainment imprint label under Interscope Records."
q_bio = "Quincy Matthew Hanley (born October 26, 1986), better known by his stage name Schoolboy Q (often stylized ScHoolboy Q), is an American hip hop recording artist from South Central Los Angeles, California. Signed to Top Dawg Entertainment and Interscope Records, Hanley is a member of hip hop supergroup Black Hippy, along with fellow West Coast rappers and label-mates Ab-Soul, Jay Rock, and Kendrick Lamar Preceded by two mixtapes, his first independent album Setbacks, released January 11, 2011, reached #100 on the US Billboard 200 chart, selling close to 1,000 digital copies in the first week. Almost a year later on January 14, 2012, he released his second independent album Habits & Contradictions. The album debuted at #111 on the US Billboard 200, with first-week sales of 3,900 digital copies in the United States. His major label debut studio album, entitled Oxymoron, was released on February 25th, 2014 & got a 81 out of 100 on Metacritic"
kw_bio = "The ubiquitous Kanye West. From his famous quip, “George Bush doesn’t care about black people” to “I'ma let you finish” to marrying Kim Kardashian, you can see that he’s a staple in the tabloids and blog posts. But that certainly doesn’t take anything away from his music. As matter of fact, it makes it better. For instance, his 2010 solo album, My Beautiful Dark Twisted Fantasy was universally praised by fans and critics alike; it was recorded during the backlash he received from the Swift interruption and during his break-up with then girlfriend Amber Rose. He has scored other well known hits as well from each of his previous studio albums, such as “Stronger,” “Homecoming,” and “Gold Digger.” Each of his albums have been massive critical and commercial successes, including his collaboration album with Jay-Z, Watch the Throne. Kanye’s most recent project was Yeezus, his sixth solo album, which polarized his fan base and the general public, but was heaped with rave reviews by music critics."
nas_bio="Nasir bin Olu Dara Jones[1] (/nɑːˈsɪər/; born September 14, 1973), better known as Nas /ˈnɑːz/, is an American rapper, songwriter, record producer, and actor. The son of jazz musician Olu Dara, Nas has released eight consecutive platinum and multi-platinum albums and sold over 25 million records worldwide since 1994. He is also an entrepreneur through his own record label; he serves as associate publisher of Mass Appeal magazine and is the owner of a Fila sneaker store. He is currently signed to Def Jam Recordings and Mass Appeal Records. NAS performing at the 2015 Sugar Mountain festival, Melbourne, Australia His musical career began in 1991 when he was featured on Main Source's track Live at the Barbeque. His debut album Illmatic, released in 1994, received universal acclaim from both critics and the hip hop community; it is frequently ranked as one of the greatest hip hop albums of all time. He did Illmatic's N.Y. State of Mind in one take."
yb_bio="Yasiin Bey, (born Dante Terrell Smith) formerly known by his stage name Mos Def, is an actor and hip hop artist from Brooklyn, New York. He is one of the founding fathers of conscious hip hop and half of the duo Black Star. Beginning in 2012, he ditched his stage name Mos Def in favor of Yasiin Bey, saying: “I began to fear that Mos Def was being treated as a product, not a person, so I’ve been going by Yasiin since ‘99. At first it was just for friends and family, but now I’m declaring it openly.” He made his musical debut in 1998 as a part of Black Star (see Mos Def & Talib Kweli are Black Star), and then released his first solo album in 1999, Black on Both Sides."
g_bio="Gerald Earl Gillum (born May 24, 1989) better known by his stage name G-Eazy or Young Gerald, is an American rapper, songwriter and producer born and raised in Oakland, California. G-Eazy has released numerous mixtapes and EP's, but his most recent release is his debut label studio album These Things Happen. His 2014 album These Things Happen peaked at number one on various charts, including a peak at number three on the Billboard 200. In July 2014, G-Eazy was placed on MTV's Artists to Watch, following a successful worldwide sold-out tour and his top selling debut album. He finished his next album The Rise Of The Villain which will release in the near future."
jz_bio="Shawn Corey Carter (born December 4, 1969), known by his stage name Jay Z (formerly Jay-Z), is an American rapper, record producer, and entrepreneur. He is one of the most financially successful hip hop artists and entrepreneurs in America. In 2014, Forbes estimated Jay Z's net worth at nearly $520 million. He is one of the world's best-selling artists of all time, having sold more than 100 million records, while receiving 21 Grammy Awards for his musical work, and numerous additional nominations. Consistently ranked as one of the greatest rappers ever, he was ranked number one by MTV in their list of The Greatest MCs of All-Time in 2006.Three of his albums, Reasonable Doubt (1996), The Blueprint (2001), and The Black Album (2003), are considered landmarks in the genre with all of them featured in Rolling Stone‍ '​s list of the 500 greatest albums of all time."
tc_bio="yler Gregory Okonma (born March 6, 1991), better known by his stage name Tyler, The Creator, is an American rapper and record producer from California. Born in Ladera Heights, he rose to prominence as the leader and co-founder of the alternative hip hop collective Odd Future, and has rapped on and produced songs for nearly every Odd Future release.[6] Okonma also creates all the artwork for the group's releases[2] and said in an interview with radio presenter DJ Semtex, that he designs all the group's clothing and other merchandise as well. After releasing his debut album Goblin under XL Recordings, in April 2011, he signed a joint venture deal for him and his label Odd Future Records, with RED Distribution and Sony Music Entertainment. Following that he released his second studio album Wolf, which was met with generally positive reviews and debuted at number three on the US Billboard 200 selling 90,000 copies in its first week."
fo_bio="Christopher Francis Ocean (born Christopher Breaux[9] October 28, 1987), is an American singer, songwriter and rapper. Ocean started his career as a ghostwriter for artists such as Damienn Jones, John Legend, Justin Bieber, and Brandy. In 2010, he became a member of alternative hip hop collective OFWGKTA also known as Odd Future, and his debut mixtape, Nostalgia, Ultra, was released to critical acclaim in 2011. The singles Novacane and Swim Good both achieved chart success. In 2012, Ocean finished second place in the BBC's Sound of 2012 poll. His debut studio album, Channel Orange, was released in July 2012 to critical acclaim and was promoted with three charting singles: Thinkin Bout You, Pyramids, and Sweet Life.Ocean became one of the first major African-American music artists to announce that he had once fallen in love with someone of the same sex.Ocean's music has been characterized by music writers as idiosyncratic in style."

# Artist.create(name:"Kendrick Lamar", img:"https://flavorwire.files.wordpress.com/2014/12/kendrick.jpg", bio:k_bio)
# Artist.create(name:"Schoolboy Q", img:"http://images.rapgenius.com/0fa28463260e245a4876dbda4609d692.576x384x1.jpg", bio:q_bio)
# Artist.create(name:"Kanye West", img:"http://imgur.com/7o6YBOP", bio:kw_bio)
# Artist.create(name:"Nas", img:"http://imgur.com/5XrxUrS" , bio:nas_bio)
# Artist.create(name:"Yasiin Bey", img:"http://imgur.com/9UcZ6iW", bio:yb_bio)
# Artist.create(name:"Jay Z", img:"http://imgur.com/6Awlc2J", bio:jz_bio)
# Artist.create(name:"G Eazy", img:"http://imgur.com/EI0pIlp", bio:g_bio)
# Artist.create(name:"tyler the creator", img:"http://imgur.com/npyvWg2", bio:tc_bio)
Artist.create(name:"Frank Ocean", img:"http://imgur.com/vxGIrcf")
